modLoader="javafml"
loaderVersion="[37,)"
license="MIT"

[[mods]]
modId="examplelib"
version="${file.jarVersion}"
displayName="Example Lib"
authors="Example Author"
description='''
This is an example library
'''

[[dependencies.examplelib]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplelib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
