modLoader="javafml"
loaderVersion="[43,)"
license="source is MIT, resources are CC-BY-NC"

[[mods]]
modId="openmodularturrets"
version="${file.jarVersion}"
displayName="OpenModularTurrets"
authors="Keridos, jmlovelace, leinierperez"
description='''
This is OpenModularTurrets. A mod that lets you build modular turrets to defend your base.
'''


[[dependencies.openmodularturrets]]
    modId="omlib"
    mandatory=true
    versionRange="[4.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.openmodularturrets]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.openmodularturrets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
