// Date: 2014/09/28 02:38:17 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package omtteam.openmodularturrets.client.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelRedstoneReactor extends ModelBase {
    //fields
    private final ModelRenderer Shape2;
    private final ModelRenderer Shape1;
    private final ModelRenderer Shape3;
    private final ModelRenderer Shape4;
    private final ModelRenderer Shape5;

    public ModelRedstoneReactor() {
        textureWidth = 64;
        textureHeight = 64;

        Shape2 = new ModelRenderer(this, 5, 15);
        Shape2.addBox(-1F, 0F, 0F, 2, 1, 11);
        Shape2.setRotationPoint(0F, 15F, 0F);
        Shape2.setTextureSize(64, 64);
        Shape2.mirror = true;
        // Should setRotation be called on this shape?

        Shape5 = new ModelRenderer(this, 5, 15);
        Shape5.addBox(-1F, -3F, 0F, 2, 1, 11);
        Shape5.setRotationPoint(0F, 15F, 0F);
        Shape5.setTextureSize(64, 64);
        Shape5.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);

        Shape1 = new ModelRenderer(this, 0, 0);
        Shape1.addBox(-3F, -4F, 9F, 6, 6, 6);
        Shape1.setRotationPoint(0F, 15F, 0F);
        Shape1.setTextureSize(64, 64);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);

        Shape3 = new ModelRenderer(this, 29, 0);
        Shape3.addBox(-1F, -6F, 11F, 2, 3, 1);
        Shape3.setRotationPoint(0F, 15F, 0F);
        Shape3.setTextureSize(64, 64);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);

        Shape4 = new ModelRenderer(this, 29, 0);
        Shape4.addBox(-1F, -6F, 13F, 2, 3, 1);
        Shape4.setRotationPoint(0F, 15F, 0F);
        Shape4.setTextureSize(64, 64);
        Shape4.mirror = true;
        setRotation(Shape4, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Shape2.render(f5);
        Shape1.render(f5);
        Shape3.render(f5);
        Shape4.render(f5);
        Shape5.render(f5);
    }

    @SuppressWarnings("SameParameterValue")
    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @SuppressWarnings("SuspiciousNameCombination")
    public void setRotationForTarget(float y, float z) {
        Shape1.rotateAngleX = y;
        Shape1.rotateAngleY = z;
        Shape2.rotateAngleX = y;
        Shape2.rotateAngleY = z;
        Shape3.rotateAngleX = y;
        Shape3.rotateAngleY = z;
        Shape4.rotateAngleX = y;
        Shape4.rotateAngleY = z;
        Shape5.rotateAngleX = y;
        Shape5.rotateAngleY = z;
    }

    public void renderAll() {
        Shape1.render(0.0625F);
        Shape2.render(0.0625F);
        Shape3.render(0.0625F);
        Shape4.render(0.0625F);
        Shape5.render(0.0625F);
    }
}
