// Date: 2014/09/24 12:06:48 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package omtteam.openmodularturrets.client.render.models;

import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class ModelLaserTurret extends ModelAbstractTurret {
    // fields
    private final ModelRenderer BoxLeft;
    private final ModelRenderer BoxRight;
    private final ModelRenderer CrossBar;
    private final ModelRenderer Chamber;
    private final ModelRenderer BarUnder;
    private final ModelRenderer BarMiddle;
    private final ModelRenderer BarTop;
    private final ModelRenderer CounterWeight;

    public ModelLaserTurret() {
        super(37, 28, 15);

        Base.addBox(-6F, 7F, -6F, 12, 1, 12);
        Base.setRotationPoint(0F, 16F, 0F);
        Base.setTextureSize(64, 32);
        Base.mirror = true;
        setRotation(Base, 0F, 0F, 0F);
        Pole.addBox(-2F, 4F, -2F, 4, 4, 4);
        Pole.setRotationPoint(0F, 16F, 0F);
        Pole.setTextureSize(64, 32);
        Pole.mirror = true;
        setRotation(Pole, 0F, 0F, 0F);
        BoxUnder.addBox(-4F, 3F, -4F, 8, 1, 8);
        BoxUnder.setRotationPoint(0F, 16F, 0F);
        BoxUnder.setTextureSize(64, 32);
        BoxUnder.mirror = true;
        setRotation(BoxUnder, 0F, 0F, 0F);
        BoxLeft = new ModelRenderer(this, 0, 15);
        BoxLeft.addBox(-4F, 4F, -4F, 8, 1, 8);
        BoxLeft.setRotationPoint(0F, 16F, 0F);
        BoxLeft.setTextureSize(64, 64);
        BoxLeft.mirror = true;
        setRotation(BoxLeft, 0F, 0F, 1.570796F);
        BoxRight = new ModelRenderer(this, 0, 15);
        BoxRight.addBox(-4F, -5F, -4F, 8, 1, 8);
        BoxRight.setRotationPoint(0F, 16F, 0F);
        BoxRight.setTextureSize(64, 64);
        BoxRight.mirror = true;
        setRotation(BoxRight, 0F, 0F, 1.570796F);
        CrossBar = new ModelRenderer(this, 0, 0);
        CrossBar.addBox(-4F, -2F, 0F, 8, 1, 1);
        CrossBar.setRotationPoint(0F, 16F, 0F);
        CrossBar.setTextureSize(64, 64);
        CrossBar.mirror = true;
        setRotation(CrossBar, 0F, 0F, 0F);
        Chamber = new ModelRenderer(this, 20, 0);
        Chamber.addBox(-2F, -7F, -3F, 4, 7, 4);
        Chamber.setRotationPoint(0F, 16F, 0.1F);
        Chamber.setTextureSize(64, 64);
        Chamber.mirror = true;
        setRotation(Chamber, 0F, 0F, 0F);
        BarUnder = new ModelRenderer(this, 37, 0);
        BarUnder.addBox(-1F, -2F, -12F, 2, 1, 10);
        BarUnder.setRotationPoint(0F, 16F, 0F);
        BarUnder.setTextureSize(64, 64);
        BarUnder.mirror = true;
        setRotation(BarUnder, 0F, 0F, 0F);
        BarMiddle = new ModelRenderer(this, 39, 26);
        BarMiddle.addBox(-1F, -4F, -8F, 2, 1, 7);
        BarMiddle.setRotationPoint(0F, 16F, 0F);
        BarMiddle.setTextureSize(64, 64);
        BarMiddle.mirror = true;
        setRotation(BarMiddle, 0F, 0F, 0F);
        BarTop = new ModelRenderer(this, 37, 16);
        BarTop.addBox(-1F, -6F, -6F, 2, 1, 7);
        BarTop.setRotationPoint(0F, 16F, 0F);
        BarTop.setTextureSize(64, 64);
        BarTop.mirror = true;
        setRotation(BarTop, 0F, 0F, 0F);
        CounterWeight = new ModelRenderer(this, 0, 4);
        CounterWeight.addBox(-2F, -6F, 1F, 4, 4, 4);
        CounterWeight.setRotationPoint(0F, 17F, 0F);
        CounterWeight.setTextureSize(64, 64);
        CounterWeight.mirror = true;
        setRotation(CounterWeight, 0F, 0F, 0F);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Base.render(f5);
        Pole.render(f5);
        BoxUnder.render(f5);
        BoxLeft.render(f5);
        BoxRight.render(f5);
        CrossBar.render(f5);
        Chamber.render(f5);
        BarUnder.render(f5);
        BarMiddle.render(f5);
        BarTop.render(f5);
        CounterWeight.render(f5);
    }

    public void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    @SuppressWarnings("SuspiciousNameCombination")
    public void setRotationForTarget(float y, float z) {
        BoxUnder.rotateAngleY = z;
        BoxLeft.rotateAngleX = z;
        BoxRight.rotateAngleX = z;
        CrossBar.rotateAngleX = y;
        CrossBar.rotateAngleY = z;
        Chamber.rotateAngleX = y;
        Chamber.rotateAngleY = z;
        BarUnder.rotateAngleX = y;
        BarUnder.rotateAngleY = z;
        BarMiddle.rotateAngleX = y;
        BarMiddle.rotateAngleY = z;
        BarTop.rotateAngleX = y;
        BarTop.rotateAngleY = z;
        CounterWeight.rotateAngleX = y;
        CounterWeight.rotateAngleY = z;
    }

    public void renderAll() {
        Base.render(0.0625F);
        Pole.render(0.0625F);
        BoxUnder.render(0.0625F);
        BoxLeft.render(0.0625F);
        BoxRight.render(0.0625F);
        CrossBar.render(0.0625F);
        Chamber.render(0.0625F);
        BarUnder.render(0.0625F);
        BarMiddle.render(0.0625F);
        BarTop.render(0.0625F);
        CounterWeight.render(0.0625F);
    }

    @Override
    public boolean hasPole() {
        return true;
    }

    @Override
    public boolean hasBoxUnder() {
        return true;
    }
}
