// Date: 2015/07/19 05:52:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package openmodularturrets.client.render.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelExpander extends ModelBase {

    // fields
    public final ModelRenderer expander;

    public ModelExpander() {
        textureWidth = 64;
        textureHeight = 64;

        expander = new ModelRenderer(this, 0, 0);
        expander.addBox(-6F, -6F, -8F, 12, 12, 6);
        expander.setRotationPoint(0F, 16F, 0F);
        expander.setTextureSize(64, 64);
        expander.mirror = true;
        setRotation(expander, 0F, 0F, 0F);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void renderAll() {
        expander.render(0.0625F);
    }
}
